
language: clojure
# check that it compiles && run linters && run tests
# stop if any of them fails
script: lein do clean, compile, check, eastwood '{:exclude-namespaces [hypobus.conjectures.specs]}', test
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
